import {v4 as uuidv4} from "uuid";
import {HardnessLevel, QuestionTopic} from "@/app/models/models";

export const MadeByMe = [
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLEasy,
        text: "What is 2 + 2?",
        goodAnswer: "4",
        badAnswers: ["2", "10", "3"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLEasy,
        text: "What is the square root of 4?",
        goodAnswer: "2",
        badAnswers: ["3", "4", "16"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLMedium,
        text: "How many times could you cut a 1m long rope in half?",
        goodAnswer: "Infinite",
        badAnswers: ["two", "thousand", "1"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLHard,
        text: "Which one is not a programming language?",
        goodAnswer: "HTML",
        badAnswers: ["Python", "Ruby", "PHP"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLHard,
        text: "In which country had the chief commander of police shot a grenade launcher in his office?",
        goodAnswer: "Poland",
        badAnswers: ["Slovakia", "Hungary", "Russia"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLEasy,
        text: "Which country lost a war to emus?",
        goodAnswer: "Australia",
        badAnswers: ["USA", "China", "Brazil"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLEasy,
        text: "The biggest country in the world is: ",
        goodAnswer: "Russia",
        badAnswers: ["USA", "Hungary", "China"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLEasy,
        text: "Which type of clouds indicate a tornado is coming?",
        goodAnswer: "Murus",
        badAnswers: ["Cumulonimbus", "Stratus", "Cumulus"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLEasy,
        text: "Which animated movie had a talking duck?",
        goodAnswer: "Mickey mouse",
        badAnswers: ["Viana", "Brother bear", "Ratatouille"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLEasy,
        text: "Which movie is part of the marvel universe?",
        goodAnswer: "Vanda Vision",
        badAnswers: ["Fantastic 4", "X-men", "John Carter"],
    },
];

export const ScienceEasy = [
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLEasy,
        text: "What planet do we live on?",
        goodAnswer: "Earth",
        badAnswers: ["Mars", "Jupiter", "Venus"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLEasy,
        text: "What gas do humans need to breathe?",
        goodAnswer: "Oxygen",
        badAnswers: ["Hydrogen", "Carbon", "Nitrogen"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLEasy,
        text: "Which state of matter is water at room temperature?",
        goodAnswer: "Liquid",
        badAnswers: ["Solid", "Gas", "Plasma"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLEasy,
        text: "What organ pumps blood through the body?",
        goodAnswer: "Heart",
        badAnswers: ["Liver", "Brain", "Lung"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLEasy,
        text: "How many legs does an insect have?",
        goodAnswer: "6",
        badAnswers: ["4", "8", "10"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLEasy,
        text: "What color is the sun?",
        goodAnswer: "White",
        badAnswers: ["Yellow", "Red", "Orange"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLEasy,
        text: "Which of these is NOT a planet?",
        goodAnswer: "Pluto (technically)",
        badAnswers: ["Mars", "Venus", "Saturn"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLEasy,
        text: "What is H2O commonly known as?",
        goodAnswer: "Water",
        badAnswers: ["Oxygen", "Salt", "Hydrogen"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLEasy,
        text: "What is the freezing point of water in Celsius?",
        goodAnswer: "0",
        badAnswers: ["-10", "32", "100"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLEasy,
        text: "Which tool is used to look at stars?",
        goodAnswer: "Telescope",
        badAnswers: ["Microscope", "Binoculars", "Periscope"],
    },
];

export const ScienceMedium = [
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLMedium,
        text: "What part of the cell contains DNA?",
        goodAnswer: "Nucleus",
        badAnswers: ["Mitochondria", "Ribosome", "Cytoplasm"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLMedium,
        text: "What is the chemical symbol for gold?",
        goodAnswer: "Au",
        badAnswers: ["Ag", "Go", "Gd"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLMedium,
        text: "What planet is known for its rings?",
        goodAnswer: "Saturn",
        badAnswers: ["Mars", "Jupiter", "Neptune"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLMedium,
        text: "Which vitamin is primarily produced when exposed to sunlight?",
        goodAnswer: "Vitamin D",
        badAnswers: ["Vitamin C", "Vitamin B12", "Vitamin A"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLMedium,
        text: "What is the hardest natural substance on Earth?",
        goodAnswer: "Diamond",
        badAnswers: ["Quartz", "Steel", "Granite"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLMedium,
        text: "What is the speed of light in vacuum?",
        goodAnswer: "299,792,458 m/s",
        badAnswers: ["150,000,000 m/s", "3,000,000 m/s", "670,000,000 m/s"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLMedium,
        text: "Which scientist proposed the three laws of motion?",
        goodAnswer: "Isaac Newton",
        badAnswers: ["Albert Einstein", "Galileo Galilei", "Nikola Tesla"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLMedium,
        text: "Which element has the atomic number 1?",
        goodAnswer: "Hydrogen",
        badAnswers: ["Helium", "Oxygen", "Carbon"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLMedium,
        text: "How many bones are in the adult human body?",
        goodAnswer: "206",
        badAnswers: ["201", "210", "180"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLMedium,
        text: "Which part of the brain is responsible for vision?",
        goodAnswer: "Occipital lobe",
        badAnswers: ["Frontal lobe", "Temporal lobe", "Parietal lobe"],
    },
];

export const ScienceHard = [
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLHard,
        text: "What is the Heisenberg Uncertainty Principle related to?",
        goodAnswer: "Position and momentum",
        badAnswers: ["Mass and energy", "Time and space", "Light and gravity"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLHard,
        text: "What is the second law of thermodynamics about?",
        goodAnswer: "Entropy always increases",
        badAnswers: ["Energy cannot be created", "Objects fall due to gravity", "Atoms are indivisible"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLHard,
        text: "Which particle is responsible for the Higgs field?",
        goodAnswer: "Higgs boson",
        badAnswers: ["Photon", "Electron", "Quark"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLHard,
        text: "What element has the highest melting point?",
        goodAnswer: "Tungsten",
        badAnswers: ["Iron", "Platinum", "Titanium"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLHard,
        text: "What’s the most abundant element in the universe?",
        goodAnswer: "Hydrogen",
        badAnswers: ["Oxygen", "Helium", "Carbon"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLHard,
        text: "Which part of the electromagnetic spectrum has the shortest wavelength?",
        goodAnswer: "Gamma rays",
        badAnswers: ["Ultraviolet", "X-rays", "Microwaves"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLHard,
        text: "What is Schrödinger’s cat a metaphor for?",
        goodAnswer: "Quantum superposition",
        badAnswers: ["Time travel", "Genetic mutation", "Dark matter"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLHard,
        text: "What is the main function of the Large Hadron Collider?",
        goodAnswer: "To collide particles at high speeds",
        badAnswers: ["To photograph galaxies", "To create black holes", "To simulate gravity"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLHard,
        text: "What is the powerhouse of the cell?",
        goodAnswer: "Mitochondria",
        badAnswers: ["Nucleus", "Golgi body", "Ribosome"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTScience,
        level: HardnessLevel.HLHard,
        text: "Which scientist developed the theory of general relativity?",
        goodAnswer: "Albert Einstein",
        badAnswers: ["Stephen Hawking", "Marie Curie", "Max Planck"],
    },

];

export const HistoryEasy = [
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLEasy,
        text: "Who was the first President of the United States?",
        goodAnswer: "George Washington",
        badAnswers: ["Abraham Lincoln", "Thomas Jefferson", "Benjamin Franklin"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLEasy,
        text: "Which famous wall was built to separate East and West Berlin?",
        goodAnswer: "The Berlin Wall",
        badAnswers: ["The Great Wall", "Iron Curtain", "Wall of Europe"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLEasy,
        text: "In what year did World War II end?",
        goodAnswer: "1945",
        badAnswers: ["1940", "1939", "1950"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLEasy,
        text: "Who discovered America in 1492?",
        goodAnswer: "Christopher Columbus",
        badAnswers: ["Marco Polo", "Vasco da Gama", "Leif Erikson"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLEasy,
        text: "Which ancient civilization built the pyramids?",
        goodAnswer: "Egyptians",
        badAnswers: ["Romans", "Aztecs", "Greeks"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLEasy,
        text: "What was the name of the ship that famously sank in 1912?",
        goodAnswer: "Titanic",
        badAnswers: ["Lusitania", "Britannic", "Queen Mary"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLEasy,
        text: "Who was known as the Maid of Orléans?",
        goodAnswer: "Joan of Arc",
        badAnswers: ["Marie Antoinette", "Catherine the Great", "Queen Elizabeth I"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLEasy,
        text: "The Cold War was primarily between which two countries?",
        goodAnswer: "USA and USSR",
        badAnswers: ["Germany and France", "USA and China", "UK and Japan"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLEasy,
        text: "Who wrote the Declaration of Independence?",
        goodAnswer: "Thomas Jefferson",
        badAnswers: ["George Washington", "James Madison", "Alexander Hamilton"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLEasy,
        text: "Which empire was ruled by Julius Caesar?",
        goodAnswer: "Roman Empire",
        badAnswers: ["Greek Empire", "Ottoman Empire", "British Empire"],
    },

];

export const HistoryMedium = [
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLMedium,
        text: "What year did the French Revolution begin?",
        goodAnswer: "1789",
        badAnswers: ["1776", "1804", "1812"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLMedium,
        text: "Who was the British Prime Minister during most of World War II?",
        goodAnswer: "Winston Churchill",
        badAnswers: ["Neville Chamberlain", "Margaret Thatcher", "Tony Blair"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLMedium,
        text: "The Renaissance began in which country?",
        goodAnswer: "Italy",
        badAnswers: ["France", "Germany", "Spain"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLMedium,
        text: "Who was the last Tsar of Russia?",
        goodAnswer: "Nicholas II",
        badAnswers: ["Peter the Great", "Ivan the Terrible", "Alexander III"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLMedium,
        text: "Which war was also known as ‘The Great War’?",
        goodAnswer: "World War I",
        badAnswers: ["World War II", "The Cold War", "The Napoleonic Wars"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLMedium,
        text: "What was the Manhattan Project?",
        goodAnswer: "The development of the atomic bomb",
        badAnswers: ["A spy network", "A skyscraper initiative", "A financial plan"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLMedium,
        text: "Who led the Salt March in India?",
        goodAnswer: "Mahatma Gandhi",
        badAnswers: ["Jawaharlal Nehru", "Indira Gandhi", "Bhagat Singh"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLMedium,
        text: "Which empire used the term 'Pharaoh' for its rulers?",
        goodAnswer: "Ancient Egypt",
        badAnswers: ["Babylonian", "Roman", "Greek"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLMedium,
        text: "The Magna Carta was signed in which year?",
        goodAnswer: "1215",
        badAnswers: ["1066", "1301", "1492"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLMedium,
        text: "Who was assassinated in 1914, sparking World War I?",
        goodAnswer: "Archduke Franz Ferdinand",
        badAnswers: ["Kaiser Wilhelm II", "Tsar Nicholas II", "Winston Churchill"],
    },

];

export const HistoryHard = [
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLHard,
        text: "Which treaty ended the Thirty Years' War in 1648?",
        goodAnswer: "Treaty of Westphalia",
        badAnswers: ["Treaty of Versailles", "Treaty of Utrecht", "Treaty of Tordesillas"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLHard,
        text: "Who was the ruler of the Mongol Empire at its greatest territorial extent?",
        goodAnswer: "Kublai Khan",
        badAnswers: ["Genghis Khan", "Tamerlane", "Ogedei Khan"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLHard,
        text: "Which U.S. president served the shortest term?",
        goodAnswer: "William Henry Harrison",
        badAnswers: ["James A. Garfield", "Zachary Taylor", "Chester A. Arthur"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLHard,
        text: "What year did the Byzantine Empire fall?",
        goodAnswer: "1453",
        badAnswers: ["1492", "1401", "1506"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLHard,
        text: "Which city was known as Constantinople before being renamed?",
        goodAnswer: "Istanbul",
        badAnswers: ["Athens", "Cairo", "Baghdad"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLHard,
        text: "Who was the founder of the Achaemenid Persian Empire?",
        goodAnswer: "Cyrus the Great",
        badAnswers: ["Darius I", "Xerxes", "Artaxerxes"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLHard,
        text: "Which famous battle in 1066 changed the course of English history?",
        goodAnswer: "Battle of Hastings",
        badAnswers: ["Battle of Agincourt", "Battle of Bosworth", "Battle of Bannockburn"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLHard,
        text: "What was the name of the Aztec capital city?",
        goodAnswer: "Tenochtitlán",
        badAnswers: ["Machu Picchu", "Teotihuacan", "Cuzco"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLHard,
        text: "Which early 20th-century revolution established communism in Russia?",
        goodAnswer: "The October Revolution",
        badAnswers: ["The February Revolution", "The Red Rebellion", "The People's Uprising"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTHistory,
        level: HardnessLevel.HLHard,
        text: "The Opium Wars were fought between China and which European power?",
        goodAnswer: "Britain",
        badAnswers: ["France", "Portugal", "The Netherlands"],
    },
];

export const MoviesEasy = [
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLEasy,
        text: "Which movie features a young wizard named Harry?",
        goodAnswer: "Harry Potter",
        badAnswers: ["The Lord of the Rings", "Percy Jackson", "Twilight"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLEasy,
        text: "Who is the famous green ogre in the DreamWorks animated films?",
        goodAnswer: "Shrek",
        badAnswers: ["Hulk", "Fiona", "Donkey"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLEasy,
        text: "Which superhero is known as the Dark Knight?",
        goodAnswer: "Batman",
        badAnswers: ["Iron Man", "Superman", "Spider-Man"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLEasy,
        text: "In 'Finding Nemo', what kind of fish is Nemo?",
        goodAnswer: "Clownfish",
        badAnswers: ["Goldfish", "Tuna", "Angelfish"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLEasy,
        text: "Which film features a talking snowman named Olaf?",
        goodAnswer: "Frozen",
        badAnswers: ["Moana", "Tangled", "Brave"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLEasy,
        text: "Who directed the movie 'Jurassic Park'?",
        goodAnswer: "Steven Spielberg",
        badAnswers: ["James Cameron", "George Lucas", "Christopher Nolan"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLEasy,
        text: "Which Pixar film is about emotions inside a young girl’s mind?",
        goodAnswer: "Inside Out",
        badAnswers: ["Up", "Soul", "Coco"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLEasy,
        text: "What is the name of the toy cowboy in 'Toy Story'?",
        goodAnswer: "Woody",
        badAnswers: ["Buzz", "Jessie", "Andy"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLEasy,
        text: "Which movie features the quote, 'May the Force be with you'?",
        goodAnswer: "Star Wars",
        badAnswers: ["Star Trek", "Guardians of the Galaxy", "Dune"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLEasy,
        text: "Which animal is the main character in 'Kung Fu Panda'?",
        goodAnswer: "Panda",
        badAnswers: ["Tiger", "Monkey", "Dragon"],
    },
];

export const MoviesMedium = [
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLMedium,
        text: "Which movie won Best Picture at the Oscars in 1994, beating out Pulp Fiction and The Shawshank Redemption?",
        goodAnswer: "Forrest Gump",
        badAnswers: ["Braveheart", "Titanic", "American Beauty"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLMedium,
        text: "Which actor played Jack in the movie 'Titanic'?",
        goodAnswer: "Leonardo DiCaprio",
        badAnswers: ["Brad Pitt", "Johnny Depp", "Matt Damon"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLMedium,
        text: "Which film features the character Tyler Durden?",
        goodAnswer: "Fight Club",
        badAnswers: ["The Matrix", "Se7en", "The Machinist"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLMedium,
        text: "Which director is known for mind-bending films like 'Inception' and 'Interstellar'?",
        goodAnswer: "Christopher Nolan",
        badAnswers: ["Quentin Tarantino", "David Fincher", "Martin Scorsese"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLMedium,
        text: "What is the name of the fictional African country in 'Black Panther'?",
        goodAnswer: "Wakanda",
        badAnswers: ["Zamunda", "Genovia", "Latveria"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLMedium,
        text: "Which movie is set in a futuristic society and features a car called the DeLorean?",
        goodAnswer: "Back to the Future",
        badAnswers: ["The Matrix", "Blade Runner", "Minority Report"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLMedium,
        text: "Which Quentin Tarantino film features the characters Jules and Vincent?",
        goodAnswer: "Pulp Fiction",
        badAnswers: ["Reservoir Dogs", "Kill Bill", "Django Unchained"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLMedium,
        text: "In which movie does Tom Hanks' character live on a deserted island?",
        goodAnswer: "Cast Away",
        badAnswers: ["The Terminal", "Captain Phillips", "Sully"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLMedium,
        text: "Which animated film takes place in the Land of the Dead and features a boy named Miguel?",
        goodAnswer: "Coco",
        badAnswers: ["The Book of Life", "Encanto", "Ratatouille"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLMedium,
        text: "Who played the Joker in 'The Dark Knight' (2008)?",
        goodAnswer: "Heath Ledger",
        badAnswers: ["Joaquin Phoenix", "Jared Leto", "Christian Bale"],
    },
];

export const MoviesHard = [
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLHard,
        text: "Which director created the 1958 psychological thriller 'Vertigo'?",
        goodAnswer: "Alfred Hitchcock",
        badAnswers: ["Stanley Kubrick", "Billy Wilder", "Orson Welles"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLHard,
        text: "Which 1927 film is often credited as the first feature-length 'talkie'?",
        goodAnswer: "The Jazz Singer",
        badAnswers: ["Metropolis", "City Lights", "Nosferatu"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLHard,
        text: "In what language was the original film 'Pan’s Labyrinth' released?",
        goodAnswer: "Spanish",
        badAnswers: ["Portuguese", "Italian", "French"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLHard,
        text: "Which Japanese filmmaker directed the classic samurai film 'Seven Samurai'?",
        goodAnswer: "Akira Kurosawa",
        badAnswers: ["Hayao Miyazaki", "Kenji Mizoguchi", "Yasujiro Ozu"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLHard,
        text: "Which film holds the record for most Academy Award wins (11), tied with 'Titanic' and 'Ben-Hur'?",
        goodAnswer: "The Lord of the Rings: The Return of the King",
        badAnswers: ["Avatar", "Gone with the Wind", "Schindler’s List"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLHard,
        text: "Which 1979 sci-fi horror film famously features the tagline: 'In space, no one can hear you scream'?",
        goodAnswer: "Alien",
        badAnswers: ["The Thing", "2001: A Space Odyssey", "Solaris"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLHard,
        text: "What is the full name of the character played by Daniel Day-Lewis in 'There Will Be Blood'?",
        goodAnswer: "Daniel Plainview",
        badAnswers: ["Eli Sunday", "Frank Wheeler", "Bill the Butcher"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLHard,
        text: "Which European film won the Best Picture Oscar in 2012?",
        goodAnswer: "The Artist",
        badAnswers: ["Amour", "La La Land", "Roma"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLHard,
        text: "What 1995 crime film revitalized Robert De Niro and Al Pacino's rivalry on screen?",
        goodAnswer: "Heat",
        badAnswers: ["Casino", "The Godfather Part III", "Donnie Brasco"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTMovies,
        level: HardnessLevel.HLHard,
        text: "What was the name of the artificial intelligence system in Stanley Kubrick’s '2001: A Space Odyssey'?",
        goodAnswer: "HAL 9000",
        badAnswers: ["VIKI", "Skynet", "GERTY"],
    },

];

export const GeographyEasy = [
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLEasy,
        text: "What is the capital city of France?",
        goodAnswer: "Paris",
        badAnswers: ["London", "Berlin", "Madrid"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLEasy,
        text: "Which continent is the Sahara Desert located in?",
        goodAnswer: "Africa",
        badAnswers: ["Asia", "Australia", "South America"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLEasy,
        text: "Which ocean is the largest?",
        goodAnswer: "Pacific Ocean",
        badAnswers: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLEasy,
        text: "What is the name of the river that runs through Egypt?",
        goodAnswer: "The Nile",
        badAnswers: ["The Amazon", "The Mississippi", "The Danube"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLEasy,
        text: "Which country is shaped like a boot?",
        goodAnswer: "Italy",
        badAnswers: ["Spain", "Portugal", "Greece"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLEasy,
        text: "Mount Everest is located on the border of which two countries?",
        goodAnswer: "Nepal and China",
        badAnswers: ["India and China", "Bhutan and India", "Pakistan and Nepal"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLEasy,
        text: "What is the capital of Japan?",
        goodAnswer: "Tokyo",
        badAnswers: ["Kyoto", "Beijing", "Seoul"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLEasy,
        text: "Which U.S. state is known as the 'Sunshine State'?",
        goodAnswer: "Florida",
        badAnswers: ["California", "Arizona", "Nevada"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLEasy,
        text: "Which continent has the most countries?",
        goodAnswer: "Africa",
        badAnswers: ["Europe", "Asia", "South America"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLEasy,
        text: "What is the name of the longest river in the world?",
        goodAnswer: "The Nile",
        badAnswers: ["The Amazon", "The Yangtze", "The Mississippi"],
    },
];

export const GeographyMedium = [
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLMedium,
        text: "Which country has the most time zones?",
        goodAnswer: "Russia",
        badAnswers: ["United States", "Canada", "China"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLMedium,
        text: "Which U.S. state has the most national parks?",
        goodAnswer: "California",
        badAnswers: ["Alaska", "Utah", "Arizona"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLMedium,
        text: "What is the largest island in the world?",
        goodAnswer: "Greenland",
        badAnswers: ["New Guinea", "Borneo", "Madagascar"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLMedium,
        text: "What country is both an island and a continent?",
        goodAnswer: "Australia",
        badAnswers: ["New Zealand", "Indonesia", "Japan"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLMedium,
        text: "Which mountain range runs along the western coast of South America?",
        goodAnswer: "The Andes",
        badAnswers: ["The Rockies", "The Alps", "The Himalayas"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLMedium,
        text: "The Great Barrier Reef is located off the coast of which country?",
        goodAnswer: "Australia",
        badAnswers: ["United States", "South Africa", "Brazil"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLMedium,
        text: "What is the only country that is also a continent?",
        goodAnswer: "Australia",
        badAnswers: ["India", "Argentina", "Brazil"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLMedium,
        text: "Which is the smallest country in the world by land area?",
        goodAnswer: "Vatican City",
        badAnswers: ["Monaco", "San Marino", "Liechtenstein"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLMedium,
        text: "Which river flows through Egypt?",
        goodAnswer: "The Nile",
        badAnswers: ["The Amazon", "The Yangtze", "The Danube"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLMedium,
        text: "Which is the longest mountain range in the world?",
        goodAnswer: "The Andes",
        badAnswers: ["The Rockies", "The Himalayas", "The Alps"],
    },
];

export const GeographyHard = [
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLHard,
        text: "Which country has the most official languages?",
        goodAnswer: "South Africa",
        badAnswers: ["India", "Switzerland", "Belgium"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLHard,
        text: "What is the deepest point on Earth?",
        goodAnswer: "Challenger Deep in the Mariana Trench",
        badAnswers: ["Mount Everest", "The Dead Sea", "The Mariana Trench's surface"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLHard,
        text: "Which country has the longest coastline in the world?",
        goodAnswer: "Canada",
        badAnswers: ["Australia", "Russia", "United States"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLHard,
        text: "Which country is the world's largest producer of coffee?",
        goodAnswer: "Brazil",
        badAnswers: ["Colombia", "Vietnam", "Ethiopia"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLHard,
        text: "What is the capital of Kazakhstan?",
        goodAnswer: "Nur-Sultan",
        badAnswers: ["Almaty", "Bishkek", "Tashkent"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLHard,
        text: "What is the name of the largest desert on Earth (excluding polar deserts)?",
        goodAnswer: "Sahara Desert",
        badAnswers: ["Kalahari Desert", "Arabian Desert", "Atacama Desert"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLHard,
        text: "Which two countries share the longest international border?",
        goodAnswer: "Canada and the United States",
        badAnswers: ["Russia and Kazakhstan", "India and China", "Brazil and Argentina"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLHard,
        text: "Which is the highest capital city in the world?",
        goodAnswer: "La Paz, Bolivia",
        badAnswers: ["Quito, Ecuador", "Lima, Peru", "Bogotá, Colombia"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLHard,
        text: "What is the world's largest island that is not a continent?",
        goodAnswer: "Greenland",
        badAnswers: ["New Guinea", "Borneo", "Madagascar"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTGeography,
        level: HardnessLevel.HLHard,
        text: "Which country has the most volcanoes in the world?",
        goodAnswer: "Indonesia",
        badAnswers: ["Japan", "Chile", "Iceland"],
    },
];

export const AnimalsEasy = [
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLEasy,
        text: "Which animal is known as the 'King of the Jungle'?",
        goodAnswer: "Lion",
        badAnswers: ["Tiger", "Elephant", "Bear"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLEasy,
        text: "What is the largest mammal in the world?",
        goodAnswer: "Blue Whale",
        badAnswers: ["Elephant", "Giraffe", "Shark"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLEasy,
        text: "What animal is known for its ability to change colors?",
        goodAnswer: "Chameleon",
        badAnswers: ["Octopus", "Snake", "Cuttlefish"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLEasy,
        text: "Which bird is famous for mimicking sounds and words?",
        goodAnswer: "Parrot",
        badAnswers: ["Eagle", "Sparrow", "Owl"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLEasy,
        text: "What do you call a baby kangaroo?",
        goodAnswer: "Joey",
        badAnswers: ["Calf", "Cub", "Lamb"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLEasy,
        text: "Which animal is known for its long neck?",
        goodAnswer: "Giraffe",
        badAnswers: ["Elephant", "Camel", "Zebra"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLEasy,
        text: "What type of animal is a Komodo dragon?",
        goodAnswer: "Lizard",
        badAnswers: ["Snake", "Crocodile", "Turtle"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLEasy,
        text: "Which animal is the fastest land animal?",
        goodAnswer: "Cheetah",
        badAnswers: ["Lion", "Tiger", "Leopard"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLEasy,
        text: "What is the only mammal capable of true flight?",
        goodAnswer: "Bat",
        badAnswers: ["Bird", "Flying Squirrel", "Insect"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLEasy,
        text: "Which sea creature is known for having eight arms?",
        goodAnswer: "Octopus",
        badAnswers: ["Squid", "Jellyfish", "Starfish"],
    },
];

export const AnimalsMedium = [
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLMedium,
        text: "Which animal has the longest lifespan?",
        goodAnswer: "Bowhead Whale",
        badAnswers: ["Elephant", "Tortoise", "Blue Whale"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLMedium,
        text: "Which bird is known for migrating over 10,000 miles each year?",
        goodAnswer: "Arctic Tern",
        badAnswers: ["Swallow", "Peregrine Falcon", "Geese"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLMedium,
        text: "Which animal has the strongest bite force relative to its size?",
        goodAnswer: "Saltwater Crocodile",
        badAnswers: ["Great White Shark", "Jaguar", "Lion"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLMedium,
        text: "Which type of animal is the axolotl?",
        goodAnswer: "Amphibian",
        badAnswers: ["Reptile", "Fish", "Mammal"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLMedium,
        text: "Which species of bear is native to China?",
        goodAnswer: "Giant Panda",
        badAnswers: ["Polar Bear", "Grizzly Bear", "Black Bear"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLMedium,
        text: "What is the largest species of shark?",
        goodAnswer: "Whale Shark",
        badAnswers: ["Great White Shark", "Tiger Shark", "Hammerhead Shark"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLMedium,
        text: "Which animal is known to have the best sense of smell?",
        goodAnswer: "Bloodhound",
        badAnswers: ["Shark", "Elephant", "Bat"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLMedium,
        text: "Which mammal is known to give birth to the largest offspring?",
        goodAnswer: "Blue Whale",
        badAnswers: ["Elephant", "Giraffe", "Hippo"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLMedium,
        text: "Which animal's tongue can be up to 2.5 times its body length?",
        goodAnswer: "Hummingbird",
        badAnswers: ["Anteater", "Giraffe", "Snake"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLMedium,
        text: "Which insect is known for its ability to communicate by dancing?",
        goodAnswer: "Honeybee",
        badAnswers: ["Ant", "Fly", "Moth"],
    },
];

export const AnimalsHard = [
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLHard,
        text: "Which animal has the largest eyes relative to its body size?",
        goodAnswer: "Mantis Shrimp",
        badAnswers: ["Owl", "Squid", "Giant Squid"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLHard,
        text: "Which mammal is known to be the fastest swimmer?",
        goodAnswer: "Common Dolphin",
        badAnswers: ["Orca", "Shark", "Seal"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLHard,
        text: "What is the name of the world's smallest mammal?",
        goodAnswer: "Etruscan Shrew",
        badAnswers: ["Bumblebee Bat", "Pygmy Jerboa", "Kitti’s Hog-nosed Bat"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLHard,
        text: "Which animal has the longest migration of any mammal?",
        goodAnswer: "Gray Whale",
        badAnswers: ["Arctic Tern", "Caribou", "Monarch Butterfly"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLHard,
        text: "Which species of frog is known to freeze solid during winter and thaw out in the spring?",
        goodAnswer: "Wood Frog",
        badAnswers: ["Bullfrog", "Tree Frog", "Leopard Frog"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLHard,
        text: "Which animal’s milk has the highest fat content?",
        goodAnswer: "Seal",
        badAnswers: ["Cow", "Goat", "Elephant"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLHard,
        text: "Which animal has the most complex brain after humans?",
        goodAnswer: "Dolphin",
        badAnswers: ["Elephant", "Chimpanzee", "Octopus"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLHard,
        text: "What is the longest-lived species of tortoise?",
        goodAnswer: "Galápagos Tortoise",
        badAnswers: ["Aldabra Giant Tortoise", "Leopard Tortoise", "Sulcata Tortoise"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLHard,
        text: "Which animal’s blood is blue due to the presence of copper?",
        goodAnswer: "Horseshoe Crab",
        badAnswers: ["Octopus", "Squid", "Jellyfish"],
    },
    {
        id: uuidv4(),
        topic: QuestionTopic.QTAnimals,
        level: HardnessLevel.HLHard,
        text: "Which type of bat is capable of echolocation and has a diet primarily of fruit?",
        goodAnswer: "Flying Fox",
        badAnswers: ["Vampire Bat", "Little Brown Bat", "Pipistrelle"],
    },
];